TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/TripKitUI.java, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/core/module/AutoCompleteRoutingComponent.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/core/module/AutoCompleteRoutingModule.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/core/module/ViewModelModule.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/routing/autocompleter/RouteAutocompleteViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/routing/autocompleter/sample/RouteAutoCompleteSampleFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/utils/RxExtension.kt, TripKitAndroidUI/src/main/res/layout/fragment_route_auto_complet_sample.xml
[18080] route search implementation
[18363] route details implementation
=> https://redmine.buzzhives.com/issues/18080 and https://redmine.buzzhives.com/issues/18363

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/timetables/data/DepartureFilter.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/timetables/data/DepartureRequestBody.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/timetables/data/DeparturesRepositoryImpl.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/timetables/domain/DeparturesRepository.kt
[18440] add route direction filter to departures.json
=> https://redmine.buzzhives.com/issues/18440

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/timetables/data/DeparturesRepositoryImpl.kt, TripKitAndroidUI/src/main/res/values/colors.xml
=> https://redmine.buzzhives.com/issues/18682

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresults/TripResultListViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresults/TripSegmentViewModel.kt, TripKitAndroidUI/src/main/res/layout/trip_result_segment_item.xml
[18683] Updated realtime handling for the trip segment list item ui
=> https://redmine.buzzhives.com/issues/18683

TripKitAndroidUI/build.gradle, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/poidetails/PoiDetailsViewModelFactory.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/timetables/TimetableViewModelFactory.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/trippreview/TripPreviewHeaderViewModelFactory.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/trippreview/nearby/SharedNearbyTripPreviewItemViewModelFactory.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/utils/ContextExtensions.kt, TripKitAndroidUIModules/TripKitAndroidUIData/build.gradle, TripKitAndroidUIModules/TripKitAndroidUIDomain/build.gradle
[19335] Update dependencies.gradle to run on latest JDK
=> https://redmine.buzzhives.com/issues/19335

TripKitAndroidUI/build.gradle, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/geocoding/RegionalGeocoder.java, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/timetables/ServiceStopFetcher.java, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/timetables/data/DeparturesRepositoryImpl.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/trippreview/nearby/SharedNearbyTripPreviewItemViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/WaypointTask.java, TripKitAndroidUIModules/TripKitAndroidUIData/build.gradle, TripKitAndroidUIModules/TripKitAndroidUIData/src/main/java/com/skedgo/tripkit/ui/data/realtime/RealTimeRepositoryImpl.kt, TripKitAndroidUIModules/TripKitAndroidUIDomain/build.gradle, build.gradle, variables.gradle
- v2.2.0 SDK update
- [19392] Publish error fixes
=> v2.2.0 release

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/core/BaseDialog.kt, TripKitAndroidUI/src/main/res/drawable/bg_top_bottom_border.xml, TripKitAndroidUI/src/main/res/values/iOS.xliff.xml
[19528] Payment method selection handling
=> https://redmine.buzzhives.com/issues/19528

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripSegmentGetOffAlertsViewModel.kt, TripKitAndroidUI/src/main/res/values/strings.xml
[odin_1.0.73] Playstore reject fixes
=> ODIN 1.0.73

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresults/TripResultListViewModel.kt
[19863] Fix outside coverage area caused by uncaught rx exception
=> https://redmine.buzzhives.com/issues/19863

TripKitAndroidUIModules/TripKitAndroidUIData/src/main/java/com/skedgo/tripkit/ui/data/location/LocationExtensions.kt
[19700] Fix Unknown values for origin and destination locations on ODIN active ticket
=> https://redmine.buzzhives.com/issues/19700

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/home/TripKitMapFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripSegmentGetOffAlertsViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripSegmentsViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/utils/ContextExtensions.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/utils/KeyConstants.kt, TripKitAndroidUI/src/main/res/values/iOS.xliff.xml
[19765] Added and initial configuration for the new NEC WL. Get off alert fix if saveURL is null for Trip.
[19823] Kill switch implementation
=> https://redmine.buzzhives.com/issues/19765 and https://redmine.buzzhives.com/issues/19823

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/controller/homeviewcontroller/TKUIHomeViewControllerFragment.kt, tripkituisample/src/main/java/com/technologies/tripkituisample/homeviewcontroller/HomeViewControllerActivity.kt
[19903] Fix bottom sheet backstack checking. Added backpress callback
[19863] Joda library update
=> https://redmine.buzzhives.com/issues/19903 and https://redmine.buzzhives.com/issues/19863

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/SegmentsPolyLineOptions.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/TripLine.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/home/TripKitMapFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripResultMapContributor.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripSegmentGetOffAlertsViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresults/TripResultListFragment.kt, TripKitAndroidUI/src/main/res/layout/list_item_search_result_item.xml
[19882] Focus trip segment waypoints on card by card trip details swipe
[19765] Adjusted instabug integration
[19901] Designs adjustments
[19879] Update permission asking for background location
=> https://redmine.buzzhives.com/issues/19882, https://redmine.buzzhives.com/issues/19765 and https://redmine.buzzhives.com/issues/19901

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/SegmentsPolyLineOptions.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/TripLine.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/home/TripKitMapFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripResultMapContributor.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripSegmentGetOffAlertsViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripSegmentsViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresults/TripResultListFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresults/actionbutton/ActionButtonHandler.kt, TripKitAndroidUI/src/main/res/layout/list_item_search_result_item.xml, TripKitAndroidUI/src/main/res/values/strings.xml
[19879] additional action alert me to control get of alerts
=> https://redmine.buzzhives.com/issues/19879

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/controller/routeviewcontroller/TKUIRouteFragment.kt
Fix wrong focus when scrolling search result list due to hiding of keyboard
=> [19933] Route card search field focus fix

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/TripKitUI.java, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/home/TripKitMapFragment.kt
[19823] put the app deactivated checker on http module to catch 401 error for all the APIs
=> [19823] App deactivation handling when tripgo key is suspended or invalid

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/dialog/GenericListAdapter.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/dialog/TripKitDateTimePickerDialogFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripSegmentGetOffAlertsViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripSegmentsViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresults/TripResultListFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/utils/ContextExtensions.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/utils/OnSwipeTouchListener.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/utils/Url.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/views/MultiStateView.kt, TripKitAndroidUI/src/main/res/values/strings.xml
- Updated targetSdkVersion to 33 for notification permission validation on android > 33
- Allow notification permission checking on app open and on turning on trip notification feature
- Handle additional subscribeURL and unsubscribeURL fields in trip
- add subscribeURL and unsubscribeURL fields to local db
- call subscribeURL when trip notification is turned on and unsubscribeURL when turned off
=> [19952] Subscribe/Unsubscribe trip notifications

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/servicedetail/AlertsAdapter.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/servicedetail/ServiceDetailFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/servicedetail/ServiceDetailViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/timetables/TimetableFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/trippreview/service/ServiceTripPreviewItemFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/utils/CustomBinding.kt, TripKitAndroidUI/src/main/res/drawable/bg_round_corner_warning.xml, TripKitAndroidUI/src/main/res/layout/item_service_alert.xml, TripKitAndroidUI/src/main/res/layout/service_detail_fragment_content.xml, TripKitAndroidUI/src/main/res/layout/timetable_fragment.xml, TripKitAndroidUI/src/main/res/layout/trip_preview_service_item.xml, TripKitAndroidUI/src/main/res/values/dimens.xml
- [20048] Handle service alerts
- Did some code cleanup
=> [20048] Service alerts

TripKitAndroidUI/src/main/res/values/dev_pref_keys.xml
show userId and fcmToken on Developer settings and add copy to clipboard functionality
=> [20047] UserID and FCM Token on developer settings

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/search/LocationSearchViewModel.kt
**Summary:**
Implemented a filter to prevent geocoding of "Current Location" on Android, enhancing location search accuracy and user experience.
**Changes:**
- Added geocode filter for "Current Location" string.
- Conducted tests to ensure functionality and reliability.
**Motivation:**
Resolves the issue of irrelevant location results when users select their current location, aligning Android app behavior with existing iOS functionality.
**Testing:**
- Manual testing.
=> [20159] Fixed current location being geocoded

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/UpdateTripForRealtime.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/utils/TapStateFlow.kt
Updated PR with review comments. Removed the logs as they are used only for troubleshooting. Also incorporated requested safe checks and magic numbers defining.
=> https://redmine.buzzhives.com/issues/19975

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/search/LocationSearchViewModel.kt
**Summary:**
Implemented a filter to prevent geocoding of "Current Location" on Android, enhancing location search accuracy and user experience.
**Changes:**
- Fixed improper conditional logic causing the search to break
**Motivation:**
Resolves the issue of irrelevant location results when users select their current location, aligning Android app behavior with existing iOS functionality.
**Testing:**
- Manual testing.
=> [20159] Fixed improper if else condition for geocode

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/MapCameraController.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/home/TripKitMapFragment.kt
**Changes**
- [TripKitUI] Focus map to selected client's region
- [TripGoSdk] Update TripGoSharedPreference to make it injectable and not initialized by application context to avoid memory leakage.
- [TripKit] Create TripKitSharedPreference to centralize handling SharePreference logic for TripKit
- [TripGoSdk & TripKit] Setup MockK
- [TripGoSdk] Written unit test for the new TripGoSharedPreference class
- [TripKit] Written unit test for the new TripKitSharedPreference class
=> [19730] Region selected focus

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/RoadTagChartAdapter.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/RoadTagChartItem.kt
[TripKitUI] Fix duplicate "Other" road tag by merging road tags in list with the same label
=> [20457] Duplicate "Other" road tag label fix

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/controller/locationsearchcontroller/TKUILocationSearchViewControllerFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/search/LocationSearchFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/search/LocationSearchViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/search/SuggestionViewModel.kt, TripKitAndroidUI/src/main/res/layout/list_item_search_result_item.xml
- [TripKitUI] Enable timetable view icon on search flag. 
- [TripKitUI] Handle timetable view icon on search action
- [TripKitUI] Small code cleanup by breaking down a long method in LocationSearchViewModel
- [TripGov5] updated classes listening on search item click
=> [20252] Timetable view in Search

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/MapExtensions.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripResultMapContributor.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripSegmentGetOffAlertsViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripSegmentListFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripSegmentsViewModel.kt, TripKitAndroidUI/src/main/res/values/colors.xml
- [TripKit] Update GeofenceBroadcastReceiver pendingIntent to fix adding data that displaces existing data within the intent.
- [TripKit] Fix geofence expiration time computation.
- [TripKit] Fix setting geofence transition type
- [TripKitUI] Showing circle on map as geofence indicator, for debugging purposes 
- [TripGov5&TripKit] Adding config to enable showing geofences on debug mode 
- [TripKitUI] Added checking to show pop-up message when device location is turned off when user switched on Trip notification toggle.
=> [20464] Destination notification fix

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresults/TripResultViewModel.kt, TripKitAndroidUI/src/main/res/color/bg_button_color_primary.xml, TripKitAndroidUI/src/main/res/layout/trip_result_list_item.xml
- [TripKitUI] Handle availabilityInfo and moneyUSDCost from response and show in trip list item. 
- [TripKit] Updated database version and add availability, availabilityInfo and moneyUSDCost fields for local storage.
=> [20422] Handle and show availability info and disabling item if availability is MISSED_PREBOOKING_WINDOW

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/search/LocationSearchViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/search/SearchCustomBinding.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/search/SuggestionViewModel.kt, TripKitAndroidUI/src/main/res/layout/list_item_search_result_item.xml
- Highlight words matched on the search result title and subtitle using BindingAdapter. 
- Update search results viewmodel classes to include term or word searched.
=> [20419] Search matched words highlight

TripKitAndroidUI/src/main/res/color/color_primary_alpha_40.xml, TripKitAndroidUI/src/main/res/drawable/bg_round_rect_primary_alpha.xml, TripKitAndroidUI/src/main/res/drawable/bg_round_rect_transparent_black_border.xml, TripKitAndroidUI/src/main/res/drawable/chevron_up.xml, TripKitAndroidUI/src/main/res/layout/trip_result_list_fragment.xml, TripKitAndroidUI/src/main/res/values/dimens.xml
[TripKitUI] Separate time and transport button on Trip result list screen.
=> [20417] Separate time and transport button on Trip result list screen.

TripKitAndroidUI/build.gradle, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/core/module/BookingModule.java, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/core/module/DeparturesModule.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/core/module/RealTimeRepositoryModule.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/core/module/TripKitUIModule.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/core/module/TripProgressModule.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/core/settings/DeveloperPreferenceRepositoryImpl.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/data/waypoints/WaypointsModule.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/AlertMarkerIconFetcher.java, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/VehicleMarkerIconFetcher.java, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/payment/PaymentData.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/utils/StopMarkerUtils.kt, TripKitAndroidUIModules/TripKitAndroidUIData/build.gradle, TripKitAndroidUIModules/TripKitAndroidUIDomain/build.gradle
- [TripKitUI][TripKit] Handle warning on payment response if return trip was not booked.
- [TripKitUI][TripKit] Handle error from server if outbound trip was not booked 
- [TripGov5][TripKitUI] Update logic related to DRT footer action.
- [TripGov5][TripKitUI][TripKit] staging build type with staging configuration changes for waupaca(Catch a ride)
=> [20495] Handle outbound and return trip booking failures from server DRT. Revisit and revamp certain logics within the DRT feature.

.github/PULL_REQUEST_TEMPLATE.md
Introducing `PULL_REQUEST_TEMPLATE.md` to enhance the quality and consistency of PR submissions. This template ensures all necessary details are included for an efficient review process.
```markdown
- **Type**: (Bug Fix / Feature / Refactor / Regression Fix)
- **Issue Link**: [Issue](https://redmine.buzzhives.com/issues/[XXXXX])
- **Risk Factor**: (Low / Medium / High)
- Detailed description of changes.
- Documentation and Code Quality
- Testing and Reliability
- Error Handling and Logging
- Steps for testing the changes.
- List of unfinished tasks.
=> [PR-REQUEST-FORMAT] Created a format to be followed when creating PR request

TripKitAndroidUI/src/main/res/layout/timetable_fragment_list_item.xml
**Ticket Link**
https://redmine.buzzhives.com/issues/15146?issue_count=17&issue_position=13&next_issue_id=14958&prev_issue_id=15983
=> [15146] Made alternative bus selection more user friendly

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/booking/apiv2/BookingV2ListResponse.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/core/module/BookingModule.java, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/dialog/GenericListItem.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/payment/PaymentSummaryDetails.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/trippreview/drt/DrtTicketViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/ActionButtonViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresult/TripSegmentsViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresults/actionbutton/ActionButtonHandler.kt, TripKitAndroidUI/src/main/res/drawable/bg_round_corner_grey.xml, TripKitAndroidUI/src/main/res/layout/trip_segment_action_button.xml, TripKitAndroidUI/src/main/res/values/iOS.xliff.xml
- [TripKitUI] Update ActionButtonHandler to add showTicket tag and handle custom action
- [TripKitUI] update ActionButtonViewModel to add function to control loader
- [TripKit] add new QuickBookingRepository
- [TripKitUI] update BookingModule to add injection for QuickBookingRepository
- [TripKit] update Ticket, PurchasedTicket and adjust names align naming on backend response
- [TripGov5] add qr generator library
- [TripGov5] add ticket qr code dialog
- [TripGov5] update HomeFragment and handle new events for ticket Qr code
- [TripGov5] update NECApplication and enable flag for token transit
- [TripGov5] updated Packages and include list for packages with transit ticket and handle external actions
- [TripKit] updated QuickBooking and added functions for converting to entity and vice …
=> [20569] QR Code for ticket handling 

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/TripKitUI.java, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/utils/CustomBinding.kt
- [TripGoV5] Handle ActiveBookingItem visibility on user logout. 
- [TripKit]Adjust AddCustomHeaders to not include empty token
- [TripGov5] check initiation in onresume for HomeBottomSheetItemManagers
- [TripKitUI] Add custom binding in CustomBinding.kt for handling view visibility by height setting
- [TripGov5] update HomeBottomSheetItemManager and add flag for including HomeItemSpacer when added to home cards
- [TripGov5] update parameters for TransitTicketItemManager and only include token provider instead of having both token provider and user account repository
- [TripGov5] Update TripGoAccountSettingsManager to add common fun clear auth and update child classes accordingly
- [TripGov5] update transit_ticket_item.xml for handling visibility (by height) when ticket polling is active …
=> [20604] Ticket update on logout and signing in with a different user fix

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/search/SearchCustomBinding.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresults/TripResultListFragment.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/tripresults/TripResultListViewModel.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/utils/CustomBinding.kt, TripKitAndroidUI/src/main/res/drawable/bg_button_accent.xml, TripKitAndroidUI/src/main/res/drawable/bg_round_corner_light_grey.xml, TripKitAndroidUI/src/main/res/drawable/bg_round_rect_accent.xml, TripKitAndroidUI/src/main/res/drawable/bg_selectable_white.xml, TripKitAndroidUI/src/main/res/drawable/bg_welcome_banner_action.xml, TripKitAndroidUI/src/main/res/layout/trip_result_list_fragment.xml, TripKitAndroidUI/src/main/res/values/colors.xml, TripKitAndroidUI/src/main/res/values/dimens.xml, TripKitAndroidUI/src/main/res/values/strings.xml
- [TripGov5] Fix ActiveBookingItemViewModel visibility and data fetching when user logged in and out.   
- [TripGov5] Add info/help icon for showing induction screen on ActiveBookingItemViewModel
- [TripGov5] Update AppSelectionFragment to cache client features and reset auth checking after selecting a region
- [TripGov5] Fix BalanceItemViewModel visibility when user logged in and out
- [TripGov5] Add info/help icon for showing induction screen on BalanceItemViewModel
- [TripKit] Update Client.kt to handle features field 
- [TripGov5] update HomeFragment to handle logic for induction home cards visibility and induction screens pop-up
- [TripGov5] new HomeInductionCardItemManager and HomeInductionCardItem for handling induction home cards
- [TripGov5] add new HomeViewModel for new logic …
=> [20424] User induction screens. [20792] Fix active trip and wallet visibility on user logout

TripKitAndroidUI/src/main/res/values-ar/iOS.xliff.xml, TripKitAndroidUI/src/main/res/values-es/iOS.xliff.xml, TripKitAndroidUI/src/main/res/values-ja/iOS.xliff.xml, TripKitAndroidUI/src/main/res/values/iOS.xliff.xml
**Title:**
If the user has not allowed location services we should see an error message
**Link:**
https://redmine.buzzhives.com/issues/20454?issue_count=18&issue_position=2&next_issue_id=20384&prev_issue_id=20726
=> [20454] Location services handling

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/trippreview/service/ServiceTripPreviewItemFragment.kt, TripKitAndroidUI/src/main/res/layout/trip_preview_service_item.xml, TripKitAndroidUI/src/main/res/values/dimens.xml, TripKitAndroidUI/src/main/res/xml/trip_preview_service_detail_motion.xml
- [TripKitUI] update ServiceTripPreviewItemFragment and remove code that set static height
- [TripKitUI] add trip_preview_service_detail_motion.xml, a separate motion layout for trip_preview_service_item.xml
- [TripKitUI] update trip_preview_service_item.xml to fix constraints of the service item recyclerview
=> [21037] Service item list layout fix

TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/TripKitUI.java, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/core/module/ScheduledStopServiceModule.java, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/core/module/TripKitUIModule.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/CreateMarkerFoFacility.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/DefaultLoadPOILocationsByViewPort.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/FacilityPOILocation.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/LoadFacilitiesByViewPort.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/map/MarkerIconManager.kt, TripKitAndroidUI/src/main/java/com/skedgo/tripkit/ui/trippreview/nearby/SharedNearbyTripPreviewItemViewModel.kt, TripKitAndroidUI/src/main/res/drawable/ic_facility.xml
- [TripKitUI] add Marker provider, CreateMarkerFoFacility, for facility
- [TripKitUI] update DefaultLoadPOILocationsByViewPort and add loading of facilities within bounds
- [TripKit] add FacilityDao to handle room db related transactions
- [TripKit] add FacilityLocationEntity model to handle facility data from location.json response
- [TripKitUI] add FacilityPOILocation, POI handling, for facility
- [TripKit] add FacilityRepository and FacilityRepositoryImpl to handle communication with room db for saving and loading facilities
- [TripKitUI] add LoadFacilitiesByViewPort for loading facilities by view port
- [TripKit] update LocationsResponse and added field for facilities
- [TripKitUI] add MarkerIconManager to process drawable and convert it to bitmap to use as marker using application …
=> [20911] Handle Facilities from location.json

TripKitAndroidUI/src/main/res/values/iOS.xliff.xml
**Issue**
Missing feature on account creation prompt - Android
**Link**
https://redmine.buzzhives.com/issues/20618
=> [20618] Missing feature on account creation prompt - Android
